name: 'Deploy'

on:
  push:
    branches:
      - master
      - dev
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Artifact
        run: |
          npm install
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cashcade-app
          path: public
