name: 'Deploy'

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Artifact
        run: |
          npm install
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: cashcade-app
          path: public

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    needs: build
    container: hashicorp/terraform

    env:
      ENVIRONMENT: dev
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: cashcade-app
          path: dist

      - name: Terraform init
        run: terraform init -backend-config="key=frontend/${ENVIRONMENT}/state"
        working-directory: terraform

      - name: Terraform plan
        run: terraform plan
        working-directory: terraform

      - name: Terraform apply
        # On push to master, build or change infrastructure according to Terraform configuration files
        #      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: terraform
